//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poligraf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public string Text { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
