//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poligraf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintMachine
    {
        public PrintMachine()
        {
            this.Schedule = new HashSet<Schedule>();
        }
    
        public int Id { get; set; }
        public string Model { get; set; }
        public int StateId { get; set; }
        public int PrintSpeedInMinute { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<Schedule> Schedule { get; set; }
    }
}
